import os as _os

_DEPS_DIR = _os.environ.get(
    "COCOMAPS_DEPS_DIR",
    _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..', 'deps'),
)

REGEX_NORMAL = r"(\d+)\s*([A-Za-z0-9]+\'{0,2}\'?)\s+([A-Za-z0-9]{1,4})\s*([a-zA-Z0-9@]{1,2})\s*(\w*\d+\w*)\s+(-?\d+\.?\d+)\s*(-?\d+\.?\d+)\s*(-?\d+\.?\d+)\s+(\d+\.?\d+)\s*(\d+\.?\d+)\s+(\w+)"
REGEX_STRING_NAMES = "([A-Za-z0-9]{1,5})\s*([A-Za-z0-9]+'{0,2}'?)\s+([A-Za-z0-9]{1,%s})\s*([a-zA-Z0-9@]{1,2})\s*(\w*\d+\w*)\s+(-?\d+\.?\d+)\s*(-?\d+\.?\d+)\s*(-?\d+\.?\d+)\s+(\d+\.?\d+)\s*(\d+\.?\d+)\s+(\w+)"
REGEX_STRING_CHAINS = "([A-Za-z0-9]{1,5})\s*([A-Za-z0-9]+'{0,2}'?)\s+([A-Za-z0-9]{1,%s})\s*([a-zA-Z0-9@]{1,%s})\s*(\w*\d+\w*)\s+(-?\d+\.?\d+)\s*(-?\d+\.?\d+)\s*(-?\d+\.?\d+)\s+(\d+\.?\d+)\s*(\d+\.?\d+)\s+(\w+)"

HB_PLUS_PATH = _os.path.join(_DEPS_DIR, "hbplus", "hbplus")
HBADD_PATH = _os.path.join(_DEPS_DIR, "hbadd", "hbadd")
HBADD_FILE_NAME = "hbplus.rc"
HBADD_EMPTY_FILE_PATH = _os.path.join(_DEPS_DIR, "hbadd", "hbadd", "hbadd_expty.txt")
HB_PLUS_OUTPUT_FILE_PATH = "./output.hb2"
HB_PLUS_FISRT_LINE = (
    "n    s   type  num  typ     dist DA aas  dist angle  dist       angle   num\n"
)
REDUCE_COMMAND = _os.path.join(_DEPS_DIR, "reduce", "reduce") + " -FLIP %s > %s"

NACCESS_PATH = _os.path.join(_DEPS_DIR, "naccess", "naccess")
NACCESS_FILE_NAME = "Rsa_stats.csv"

BEEM_PATH = _os.environ.get("COCOMAPS_BEEM_PATH", "")
CIF2PDB_COMMAND = BEEM_PATH + "/BeEM %s" if BEEM_PATH else ""
CHAIN1_IDENTIFIER = "@"
CHAIN2_IDENTIFIER = "!"

pdb_file = None
chains_set_1 = None
chains_set_2 = None
ranges_1 = None
ranges_2 = None

REDUCE_BOOL = False#

HBOND_DIST = 4.0
HBOND_ANGLE = 90

SBRIDGE_DIST = 4.5

WBRIDGE_DIST = 4.0

CH_ON_DIST = 4.4
CH_ON_ANGLE = 110

CUT_OFF = 5.0
METAL_CUTOFF = 8.0

APOLAR_TOLERANCE = 4.2
POLAR_TOLERANCE = 4.2

PI_PI_DIST = 5.5
PI_PI_THETA = 80
PI_PI_GAMMA = 90

ANION_PI_DIST = 5.0
LONEPAIR_PI_DIST = 5.0
AMINO_PI_DIST = 5.0
CATION_PI_DIST = 5.0

RISE_THRESHOLD_TYPES = {
    "cation_pi": 5.0,
    "anion_pi": 5.0,
    "polar_pi": 5.0,
    "lone_pair_pi": 5.0,
}

# WATER MEDIATED AND HYGROGEN BONDS ARE BEING GENERATED BY
# HBPLUS SOFTWARE WITH THRESHOLD DISTANCE GIVEN TO BE 4.0

# METAL DISTACES ARE FIXED AND CAN BE FOUND IN ressidues.py
METAL_DIST = 3.2

HALOGEN_THETA1 = 120
HALOGEN_THETA2 = 110
# HALOGEN DISTANCES ARE FIXED

RING_RADIUS_THRESHOLDS = {6: [2.25, 2.25], 5: [1.57, 1.57], 9: [6.25, 2.25]}

C_H_PI_DIST = 5.0
C_H_PI_THETA1 = 120
C_H_PI_THETA2 = 30

NSOH_PI_DIST = 4.5
NSOH_PI_THETA1 = 120
NSOH_PI_THETA2 = 30

SSBOND_DIST = 3.0

pdb_fromat_dict = {
    0: ((0, 5), "l"),
    1: ((6, 10), "r"),
    2: ((13, 15), "l"),
    3: ((17, 19), "r"),
    4: ((21, 21), "r"),
    5: ((22, 25), "r"),
    6: ((30, 36), "r"),
    7: ((38, 44), "r"),
    8: ((46, 52), "r"),
    9: ((54, 59), "r"),
    10: ((60, 65), "r"),
    11: ((76, 77), "r"),
}


# column names
RES_NAME_1 = "Res. Name 1"
RES_NUM_1 = "Res. Number 1"
CHAIN_1 = "Chain 1"
ATOM_1 = "Atom 1"
RES_NAME_2 = "Res. Name 2"
RES_NUM_2 = "Res. Number 2"
CHAIN_2 = "Chain 2"
ATOM_2 = "Atom 2"
DISTANCE_NAME = "Distance (Å)"
THETA_NAME = "Theta °"
GAMA_NAME = "Gamma °"
RING_FROM = "Ring From"
LONE_PAIR_ATOM = "Lone_pair Atom"
LONE_PAIR_FROM = "Lone_pair From"
ANION_ATOM = "Anion Atom"
ANION_FROM = "Anion From"
POLAR_ATOM = "Polar Atom"
POLAR_FROM = "Polar From"
CATION_ATOM = "Cation Atom"
CATION_FROM = "Cation From"
DISTANCE_FROM_RES1_NAME = "Distance from Res 1"
DISTANCE_FROM_RES2_NAME = "Distance from Res 2"
METAL_IDENTITY_NAME = "Metal Identity"
WATER_IDENTITY_NAME = "Water Identity"
C_ATOM_COULUMN = "C Atom"
H_ATOM_COULUMN = "H Atom"
C_ATOM_FROM = "C Atom From"
ALPHA_NAME = "Alpha °"
BETA_NAME = "BETA °"
DHA_ANGLE_NAME = "DHA Angle"
THETA_1_NAME = "Theta 1"
THETA_2_NAME = "Theta 2"
COMPLEX_ASA_NAME = "Complex ASA"
FRESS_ASA_NAME = "Free ASA"
BURRIED_ASA_NAME = "Buried ASA (Interface)"
BURIED_ASA_PERCENTAGE = "Buried ASA %"
ATOM_1_ORG_NAME = "Atom 1 org name"
ATOM_2_ORG_NAME = "Atom 2 org name"

TYPE_COLUMN_NAME = "Type of Interactions"

INTERACTION_NAMES = {
    "File_name": "File_name",
    "Hydrogen": "H-bond",  #
    "Hydro-Phobic": "apolar-vdw",
    "Salt-bridge": "salt bridge",
    "C-H-O_N type": "CH-O_N bond",
    "C-H_Pi": "CH_pi",
    "Water Mediated": "water-mediated",
    "Metal_Mediated": "metal-mediated",
    "N_S_O-H_Pi": "N_S_OH-pi",
    "Pi-Pi Stacking": "pi-pi stacking",
    "cation_pi": "cation-pi",
    "anion_pi": "anion-pi",
    "polar_pi": "polar-pi",
    "lone_pair_pi": "lonepair-pi",
    "Halogen_interactions": "halogen bond",
    "S-bond": "S-bond",
    "Van-der-waals": "polar-vdw",
    "Undetermined": "proximal",
}
INTERACTION_NAMES_REVERSE = {
    "File_name": "File_name",
    "H-bond": "Hydrogen",  #
    "apolar-vdw": "Hydro-Phobic",
    "salt bridge": "Salt-bridge",
    "CH-O_N bond": "C-H-O_N type",
    "CH_pi": "C-H_Pi",
    "water-mediated": "Water Mediated",
    "metal-mediated": "Metal_Mediated",
    "N_S_OH-pi": "N_S_O-H_Pi",
    "pi-pi stacking": "Pi-Pi Stacking",
    "cation-pi": "cation_pi",
    "anion-pi": "anion_pi",
    "polar-pi": "polar_pi",
    "lonepair-pi": "lone_pair_p",
    "halogen bond": "Halogen_interactions",
    "S-bond": "S-bond",
    "polar-vdw": "Van-der-waals",
    "Undetermined": "proximal",
}
BASIC_INTERACTION_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
}
PI_PI_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    DISTANCE_NAME: [],
    THETA_NAME: [],
    GAMA_NAME: [],
}
LONE_PAIR_PI_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    DISTANCE_NAME: [],
    LONE_PAIR_ATOM: [],
    LONE_PAIR_FROM: [],
    RING_FROM: [],
}
ANION_PI_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    DISTANCE_NAME: [],
    ANION_ATOM: [],
    ANION_FROM: [],
    RING_FROM: [],
}
CATION_PI_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    DISTANCE_NAME: [],
    CATION_ATOM: [],
    CATION_FROM: [],
    RING_FROM: [],
}
AMINO_PI_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    DISTANCE_NAME: [],
    POLAR_ATOM: [],
    POLAR_FROM: [],
    RING_FROM: [],
}
METAL_MEDIATED_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    ATOM_1: [],
    ATOM_2: [],
    DISTANCE_FROM_RES1_NAME: [],
    DISTANCE_FROM_RES2_NAME: [],
    METAL_IDENTITY_NAME: [],
}

C_H_PI_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    DISTANCE_NAME: [],
    C_ATOM_COULUMN: [],
    H_ATOM_COULUMN: [],
    C_ATOM_FROM: [],
    RING_FROM: [],
    ALPHA_NAME: [],
    BETA_NAME: [],
}

NSO_H_PI_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    DISTANCE_NAME: [],
    C_ATOM_COULUMN: [],
    H_ATOM_COULUMN: [],
    C_ATOM_FROM: [],
    RING_FROM: [],
    ALPHA_NAME: [],
    BETA_NAME: [],
}

WEAK_H_BONDS_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    ATOM_1: [],
    ATOM_2: [],
    DISTANCE_NAME: [],
    THETA_NAME: [],
    H_ATOM_COULUMN: [],
}

WATER_MEDIATED_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    ATOM_1: [],
    ATOM_2: [],
    DISTANCE_FROM_RES1_NAME: [],
    DISTANCE_FROM_RES2_NAME: [],
    WATER_IDENTITY_NAME: [],
}
WATER_MEDIATED_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    ATOM_1: [],
    ATOM_2: [],
    DISTANCE_FROM_RES1_NAME: [],
    DISTANCE_FROM_RES2_NAME: [],
    WATER_IDENTITY_NAME: [],
}
SALT_BRIDGE_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_1: [],
    ATOM_1: [],
    ATOM_2: [],
    DISTANCE_NAME: [],
}
HYDROGEN_BOND_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    ATOM_1: [],
    ATOM_2: [],
    DISTANCE_NAME: [],
    DHA_ANGLE_NAME: [],
}

APOLAR_VDW_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    ATOM_1: [],
    ATOM_2: [],
    DISTANCE_NAME: [],
}
POLAR_VDW_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    ATOM_1: [],
    ATOM_2: [],
    DISTANCE_NAME: [],
}

HALOGEN_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    ATOM_1: [],
    ATOM_2: [],
    THETA_1_NAME: [],
    THETA_2_NAME: [],
    DISTANCE_NAME: [],
}
CLASH_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    ATOM_1: [],
    ATOM_2: [],
    DISTANCE_NAME: [],
}
SS_BOND_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    ATOM_1: [],
    ATOM_2: [],
    DISTANCE_NAME: [],
}
SALT_BRIDGE_DICT_STRUCTURE = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    RES_NAME_2: [],
    RES_NUM_2: [],
    CHAIN_2: [],
    ATOM_1: [],
    ATOM_2: [],
    DISTANCE_NAME: [],
}

# find the meaning in the name not the variable name
TOTAL_BURRIED_AREA_NAME = "Buried area upon the complex formation / Interface area (Å²)"
TOTAL_BURRIED_PERCENTAGE_NAME = "Buried area upon the complex formation (%)"
POLAR_BURRIED_AREA_NAME = (
    "POLAR Buried area upon the complex formation / Interface area (Å²)"
)
POLAR_BURRIED_PERCENTAGE_NAME = "POLAR Interface (%)"
NON_POLAR_BURRIED_AREA_NAME = (
    "NON POLAR Buried area upon the complex formation / Interface area (Å²)"
)
NON_POLAR_BURRIED_PERCENTAGE_NAME = "NON POLAR Interface (%)"
RSA_TABLE = {
    "Property": [
        TOTAL_BURRIED_AREA_NAME,
        TOTAL_BURRIED_PERCENTAGE_NAME,
        POLAR_BURRIED_AREA_NAME,
        POLAR_BURRIED_PERCENTAGE_NAME,
        NON_POLAR_BURRIED_AREA_NAME,
        NON_POLAR_BURRIED_PERCENTAGE_NAME,
    ],
    "Value": [],
}
ASA_TABLE_PER_CHAIN = {
    RES_NAME_1: [],
    RES_NUM_1: [],
    CHAIN_1: [],
    COMPLEX_ASA_NAME: [],
    FRESS_ASA_NAME: [],
    BURRIED_ASA_NAME: [],
    BURIED_ASA_PERCENTAGE: [],
}


WEAK_H_BONDS_PRINT_NAME = "CH-O/N bond"
METAL_MEDIATED_PRINT_NAME = "Metal mediated contact"
PI_PI_PRINT_NAME = "π-π interaction"
LONE_PAIR_PI_PRINT_NAME = "lp-π interaction"
ANION_PI_PRINT_NAME = "Anion-π interaction"
CATION_PI_PRINT_NAME = "Cation-π interaction"
AMINO_PI_PRINT_NAME = "Amino-π interaction"
C_H_PI_PRINT_NAME = "CH-π interaction"
N_H_PI_PRINT_NAME = "O/N/SH-π interaction"
APOLAR_PRINT_NAME = "Apolar vdW contact"
POLAR_PRINT_NAME = "Polar vdW contact"
HYDROGEN_PRINT_NAME = "H-bond"
HALOGEN_PRINT_NAME = "Halogen bond"
WATER_MEDIATED_PRINT_NAME = "Water mediated contact"
SALT_BRIDGE_PRINT_NAME = "Salt-bridge"
HALOGEN_PI_PRINT_NAME = "Halogen-π interaction"
SS_BOND_PRINT_NAME = "S-S Bond"
CLASH_PRINT_NAME = "Clash"
PROXIMAL_PRINT_NAME = "Proximal contact"

WEAK_H_BONDS_NAME = "C-H_ON"
METAL_MEDIATED_NAME = "Metal_Mediated"
PI_PI_NAME = "pi-pi"
LONE_PAIR_PI_NAME = "Lone_pair_pi"
ANION_PI_NAME = "Anion_pi"
CATION_PI_NAME = "Cation_pi"
AMINO_PI_NAME = "Amino_pi"
C_H_PI_NAME = "C-H_pi"
N_H_PI_NAME = "N-S-O-H_pi"
APOLAR_NAME = "Apolar_vdw"
POLAR_NAME = "Polar_vdw"
HYDROGEN_NAME = "H-bond"
HALOGEN_NAME = "Halogen_bond"
WATER_MEDIATED_NAME = "Water_Mediated"
SALT_BRIDGE_NAME = "Salt_bridge"
HALOGEN_PI_NAME = "Halogen_pi"
SS_BOND_NAME = "SS_bond"
CLASH_NAME = "Clash"
PROXIMAL_NAME = "Proximal"


INTERNAL_CLASH_CHECK_INTERCATION_TYPES = [
    WEAK_H_BONDS_NAME,
    HYDROGEN_NAME,
    POLAR_NAME,
    APOLAR_NAME,
    HALOGEN_NAME,
    SS_BOND_NAME,
    SALT_BRIDGE_NAME,
]

SMALL_SUMMARY_TABLE = {
    "Property":[
        "Total Number of Interacting Residues",
        "Number of Interacting Residues in Chain 1",
        "Number of Interacting Residues in Chain 2"
        ],
    "Value":[0,0,0]
}

SUMMARY_TABLE = {
    "Property": [
        f"Number of {SS_BOND_PRINT_NAME}s",
        f"Number of {SALT_BRIDGE_PRINT_NAME}s",
        f"Number of {HYDROGEN_PRINT_NAME}s",
        f"Number of {WATER_MEDIATED_PRINT_NAME}s",
        f"Number of {WEAK_H_BONDS_PRINT_NAME}s",
        f"Number of {HALOGEN_PRINT_NAME}s",
        f"Number of {METAL_MEDIATED_PRINT_NAME}s",
        f"Number of {PI_PI_PRINT_NAME}s",
        f"Number of {LONE_PAIR_PI_PRINT_NAME}s",
        f"Number of {ANION_PI_PRINT_NAME}s",
        f"Number of {CATION_PI_PRINT_NAME}s",
        f"Number of {AMINO_PI_PRINT_NAME}s",
        f"Number of {N_H_PI_PRINT_NAME}s",
        f"Number of {C_H_PI_PRINT_NAME}s",
        f"Number of {POLAR_PRINT_NAME}s",
        f"Number of {APOLAR_PRINT_NAME}s",
        f"Number of {CLASH_PRINT_NAME}es",
        f"Number of {PROXIMAL_PRINT_NAME}s",
    ],
    "Value": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
}
DROP_ROWS = ["HOH", "SO4"]

rna_chains = "rna_chains"
ligand_name = "ligand_name"
ligand_chain = "ligand_chain"
ligand_res_num = "ligand_res_num"
LIGAND_SEQRES_ACCEPTABLES = [
    "ALA",
    "CYS",
    "ASP",
    "GLU",
    "PHE",
    "GLY",
    "HIS",
    "ILE",
    "LYS",
    "LEU",
    "MET",
    "ASN",
    "PRO",
    "GLN",
    "ARG",
    "SER",
    "THR",
    "VAL",
    "TRP",
    "TYR",
]