""" All parameters and atoms used for various types of interactions"""

a_atoms = ["N1", "C2", "N3", "C4", "C5", "C6", "N7", "C8", "N9"]
g_atoms = ["N1", "C2", "N3", "C4", "C5", "C6", "N7", "C8", "N9"]
u_atoms = ["N1", "C2", "N3", "C4", "C5", "C6"]
c_atoms = ["N1", "C2", "N3", "C4", "C5", "C6"]
psu_atoms = ["N1", "C2", "N3", "C4", "C5", "C6"]
da_atoms = ["N1", "C2", "N3", "C4", "C5", "C6", "N7", "C8", "N9"]
dg_atoms = ["N1", "C2", "N3", "C4", "C5", "C6", "N7", "C8", "N9"]
dc_atoms = ["N1", "C2", "N3", "C4", "C5", "C6"]
dt_atoms = ["N1", "C2", "N3", "C4", "C5", "C6"]
trp_atoms = ["CG", "CD1", "NE1", "CE2", "CD2", "CE3", "CZ3", "CZ2", "CH2"]
tyro_atoms = ["CG", "CD1", "CE1", "CZ", "CD2", "CE2"]
his_atoms = ["ND1", "CG", "CE1", "NE2", "CD2"]
phe_atoms = ["CG", "CD1", "CD2", "CE1", "CE2", "CZ"]


residues = {
    "A": a_atoms,
    "G": g_atoms,
    "U": u_atoms,
    "C": c_atoms,
    "PSU": psu_atoms,
    "DG": dg_atoms,
    "DA": da_atoms,
    "DC": dc_atoms,
    "DT": dt_atoms,
    "TYR": tyro_atoms,
    "ATYR": tyro_atoms,
    "BTYR": tyro_atoms,
    "TRP": trp_atoms,
    "ATRP": trp_atoms,
    "BTRP": trp_atoms,
    "HIS": his_atoms,
    "AHIS": his_atoms,
    "BHIS": his_atoms,
    "PHE": phe_atoms,
    "APHE": phe_atoms,
    "BPHE": phe_atoms,
    "8AN": a_atoms,
    "1MA": a_atoms,
    "AMP": a_atoms,
    "MTA": a_atoms,
    "A2M": a_atoms,
    "N6G": a_atoms,
    "2IA": a_atoms,
    "0A": a_atoms,
    "DTP": a_atoms,
    "A7C": a_atoms,
    "A44/": a_atoms,
    "SAH": a_atoms,
    "APC": a_atoms,
    "2MA": a_atoms,
    "7AT": a_atoms,
    "45A": a_atoms,
    "ZAD": a_atoms,
    "MIA": a_atoms,
    "PPU": a_atoms,
    "1DP": a_atoms,
    "A6A": a_atoms,
    "12A": a_atoms,
    "4M2/": a_atoms,
    "EEM": a_atoms,
    "CVC": a_atoms,
    "RIA": a_atoms,
    "QSQ": a_atoms,
    "F7O": a_atoms,
    "6MA": a_atoms,
    "A23/": a_atoms,
    "XAR": a_atoms,
    "6MZ": a_atoms,
    "LCA": a_atoms,
    "6HA": a_atoms,
    "31M": a_atoms,
    "3DA": a_atoms,
    "ATP": a_atoms,
    "AF2/": a_atoms,
    "F3N": a_atoms,
    "F6U": a_atoms,
    "A7E": a_atoms,
    "6MD": a_atoms,
    "AT7/": a_atoms,
    "PU": a_atoms,
    "6IA": a_atoms,
    "T6A": a_atoms,
    "P5P": a_atoms,
    "MA6/": a_atoms,
    "31H": a_atoms,
    "2BA": a_atoms,
    "ADN": a_atoms,
    "2AD": a_atoms,
    "AVC": a_atoms,
    "5AA": a_atoms,
    "M7A": a_atoms,
    "4BW": a_atoms,
    "SAM": a_atoms,
    "APN": a_atoms,
    "E7X": a_atoms,
    "ADS": a_atoms,
    "DSH": a_atoms,
    "Y5P": u_atoms,
    "UR3/": u_atoms,
    "UMO": u_atoms,
    "H2U": u_atoms,
    "A6U": u_atoms,
    "5IU": u_atoms,
    "UFB": u_atoms,
    "IU": u_atoms,
    "P4U": u_atoms,
    "2MU": u_atoms,
    "U4M": u_atoms,
    "U36/": u_atoms,
    "UOA": u_atoms,
    "HYG": u_atoms,
    "U33/": u_atoms,
    "0U": u_atoms,
    "2AU": u_atoms,
    "4SU": u_atoms,
    "UFT": u_atoms,
    "UTP": u_atoms,
    "OMU": u_atoms,
    "DOL": u_atoms,
    "6FU": u_atoms,
    "J48/": u_atoms,
    "URU": u_atoms,
    "5FU": u_atoms,
    "RUS": u_atoms,
    "H2U20^A": u_atoms,
    "UZR": u_atoms,
    "0U1/": u_atoms,
    "5BU": u_atoms,
    "UOB": u_atoms,
    "SSU": u_atoms,
    "BRU": u_atoms,
    "SUR": u_atoms,
    "UMS": u_atoms,
    "I4U": u_atoms,
    "U5M": u_atoms,
    "US5/": u_atoms,
    "U23/": u_atoms,
    "T5S": u_atoms,
    "U5R": u_atoms,
    "ZBU": u_atoms,
    "2KH": u_atoms,
    "C2E": g_atoms,
    "P7G": g_atoms,
    "DGP": g_atoms,
    "GDO": g_atoms,
    "B8W": g_atoms,
    "XUG": g_atoms,
    "PGN": g_atoms,
    "5GP": g_atoms,
    "ZGU": g_atoms,
    "M2G": g_atoms,
    "F73/": g_atoms,
    "HPA": g_atoms,
    "MHG": g_atoms,
    "GT3/": g_atoms,
    "B8K": g_atoms,
    "LCG": g_atoms,
    "G2P": g_atoms,
    "GRB": g_atoms,
    "GUN": g_atoms,
    "Q61/": g_atoms,
    "OMG": g_atoms,
    "E6G": g_atoms,
    "GNG": g_atoms,
    "5CG": g_atoms,
    "2MG": g_atoms,
    "QUO": g_atoms,
    "I": g_atoms,
    "7MG": g_atoms,
    "GMP": g_atoms,
    "PRF": g_atoms,
    "GNP": g_atoms,
    "G48/": g_atoms,
    "1MG": g_atoms,
    "B9B": g_atoms,
    "XGR": g_atoms,
    "GMX": g_atoms,
    "G4P": g_atoms,
    "F7U": g_atoms,
    "PGP": g_atoms,
    "0G": g_atoms,
    "G46/": g_atoms,
    "GDP": g_atoms,
    "23G": g_atoms,
    "BGM": g_atoms,
    "GPN": g_atoms,
    "Q1V": g_atoms,
    "G7M": g_atoms,
    "6HG": g_atoms,
    "MTU": g_atoms,
    "TG": g_atoms,
    "BGH": g_atoms,
    "SDG": g_atoms,
    "G5J": g_atoms,
    "GTP": g_atoms,
    "F7X": g_atoms,
    "E7G": g_atoms,
    "G47/": g_atoms,
    "2SG": g_atoms,
    "GF2/": g_atoms,
    "A6G": g_atoms,
    "1SC": c_atoms,
    "BLS": c_atoms,
    "5CF": c_atoms,
    "CTP": c_atoms,
    "AG9/": c_atoms,
    "1CC": c_atoms,
    "A6C": c_atoms,
    "N5M": c_atoms,
    "E3C": c_atoms,
    "S4C": c_atoms,
    "ZCY": c_atoms,
    "CFL": c_atoms,
    "CCC": c_atoms,
    "6HC": c_atoms,
    "OMC": c_atoms,
    "B9H": c_atoms,
    "O2C": c_atoms,
    "CFZ": c_atoms,
    "6FC": c_atoms,
    "B8Q": c_atoms,
    "5HM": c_atoms,
    "XCR": c_atoms,
    "DCZ": c_atoms,
    "C43/": c_atoms,
    "F6X": c_atoms,
    "CBV": c_atoms,
    "B8T": c_atoms,
    "QSK": c_atoms,
    "NCU": c_atoms,
    "LCC": c_atoms,
    "A5M": c_atoms,
    "5MC": c_atoms,
    "F7R": c_atoms,
    "LHH": c_atoms,
    "CBR": c_atoms,
    "N5C": c_atoms,
    "CPN": c_atoms,
    "M5M": c_atoms,
    "LV2/": c_atoms,
    "CSL": c_atoms,
    "0C": c_atoms,
    "JMH": c_atoms,
    "5CM": c_atoms,
    "73W": c_atoms,
    "5IC": c_atoms,
    "RSP": c_atoms,
    "DCT": c_atoms,
    "RSQ": c_atoms,
    "DOC": c_atoms,
    "4AC": c_atoms,
    "4OC": c_atoms,
    "70U": u_atoms,
    "T2T": u_atoms,
    "2MU": u_atoms,
    "CM0/": u_atoms,
    "5MU": u_atoms,
    "US3/": u_atoms,
    "TM2/": u_atoms,
    "TPN": u_atoms,
    "ZTH": u_atoms,
    "2QB": u_atoms,
    "XTR": u_atoms,
    "75B": u_atoms,
    "6HT": u_atoms,
    "6F7/": u_atoms,
    "MNU": u_atoms,
    "U8U": u_atoms,
    "TLN": u_atoms,
    "NTT": u_atoms,
    "8RJ": u_atoms,
}

Modified_t = {
    "70U",
    "T2T",
    "2MU",
    "CM0/",
    "5MU",
    "US3/",
    "TM2/",
    "TPN",
    "ZTH",
    "2QB",
    "XTR",
    "75B",
    "6HT",
    "6F7/",
    "MNU",
    "U8U",
    "TLN",
    "NTT",
    "8RJ",
}

Modified_c = {
    "1SC",
    "BLS",
    "5CF",
    "CTP",
    "AG9/",
    "1CC",
    "A6C",
    "N5M",
    "E3C",
    "S4C",
    "ZCY",
    "CFL",
    "CCC",
    "6HC",
    "OMC",
    "B9H",
    "O2C",
    "CFZ",
    "6FC",
    "B8Q",
    "5HM",
    "XCR",
    "DCZ",
    "C43/",
    "F6X",
    "CBV",
    "B8T",
    "QSK",
    "NCU",
    "LCC",
    "A5M",
    "5MC",
    "F7R",
    "LHH",
    "CBR",
    "N5C",
    "CPN",
    "M5M",
    "LV2/",
    "CSL",
    "0C",
    "JMH",
    "5CM",
    "73W",
    "5IC",
    "RSP",
    "DCT",
    "RSQ",
    "DOC",
    "4AC",
    "4OC",
}

Modified_g = {
    "C2E",
    "P7G",
    "DGP",
    "GDO",
    "B8W",
    "XUG",
    "PGN",
    "5GP",
    "ZGU",
    "M2G",
    "F73/",
    "HPA",
    "MHG",
    "GT3/",
    "B8K",
    "LCG",
    "G2P",
    "GRB",
    "GUN",
    "Q61/",
    "OMG",
    "E6G",
    "GNG",
    "5CG",
    "2MG",
    "QUO",
    "7MG",
    "GMP",
    "PRF",
    "GNP",
    "G48/",
    "1MG",
    "B9B",
    "XGR",
    "GMX",
    "G4P",
    "F7U",
    "PGP",
    "0G",
    "G46/",
    "GDP",
    "23G",
    "BGM",
    "GPN",
    "Q1V",
    "G7M",
    "6HG",
    "MTU",
    "TG",
    "BGH",
    "SDG",
    "G5J",
    "GTP",
    "F7X",
    "E7G",
    "G47/",
    "2SG",
    "GF2/",
    "A6G",
}

Modified_u = {
    "Y5P",
    "UR3/",
    "UMO",
    "H2U",
    "A6U",
    "5IU",
    "UFB",
    "IU",
    "P4U",
    "2MU",
    "U4M",
    "U36/",
    "UOA",
    "HYG",
    "U33/",
    "0U",
    "2AU",
    "4SU",
    "UFT",
    "UTP",
    "OMU",
    "DOL",
    "6FU",
    "J48/",
    "URU",
    "5FU",
    "RUS",
    "H2U20^A",
    "UZR",
    "0U1/",
    "5BU",
    "UOB",
    "SSU",
    "BRU",
    "SUR",
    "UMS",
    "I4U",
    "U5M",
    "US5/",
    "U23/",
    "T5S",
    "U5R",
    "ZBU",
    "2KH",
}

Modified_a = {
    "0A",
    "12A",
    "1DP",
    "1MA",
    "2AD",
    "2BA",
    "2IA",
    "2MA",
    "31H",
    "31M",
    "3DA",
    "45A",
    "4BW",
    "4M2/",
    "5AA",
    "6HA",
    "6IA",
    "6MA",
    "6MD",
    "6MZ",
    "7AT",
    "8AN",
    "A23/",
    "A2M",
    "A44/",
    "A6A",
    "A7C",
    "A7E",
    "ADN",
    "ADS",
    "AF2/",
    "AMP",
    "APC",
    "APN",
    "AT7/",
    "ATP",
    "AVC",
    "CVC",
    "DSH",
    "DTP",
    "E7X",
    "EEM",
    "F3N",
    "F6U",
    "F7O",
    "LCA",
    "M7A",
    "MA6/",
    "MIA",
    "MTA",
    "N6G",
    "P5P",
    "PPU",
    "PU",
    "QSQ",
    "RIA",
    "SAH",
    "SAM",
    "T6A",
    "XAR",
    "ZAD",
}

all_ring_names = list(residues.keys())


cation_pi = {
    "ARG": ["NE", "CZ", "NH1", "NH2"],
    "AARG": ["NE", "CZ", "NH1", "NH2"],
    "BARG": ["NE", "CZ", "NH1", "NH2"],
    "CARG": ["NE", "CZ", "NH1", "NH2"],
    "LYS": ["CE", "NZ"],
    "ALYS": ["CE", "NZ"],
    "BLYS": ["CE", "NZ"],
    "CLYS": ["CE", "NZ"],
    # "HIS": ["ND1", "NE2"],
    # "HIP": ["ND1", "NE2"],
}

amino_pi = {
    "ASN": ["ND2"],
    "AASN": ["ND2"],
    "BASN": ["ND2"],
    "GLN": ["NE2"],
    "AGLN": ["NE2"],
    "BGLN": ["NE2"],
    "A": ["N6"],
    "G": ["N2"],
    "C": ["N4"],
    "DA": ["N6"],
    "DG": ["N2"],
    "DC": ["N4"],
}

anion_pi = {
    "GLU": ["OE1", "OE2"],
    "AGLU": ["OE1", "OE2"],
    "BGLU": ["OE1", "OE2"],
    "CGLU": ["OE1", "OE2"],
    "ASP": ["OD1", "OD2"],
    "AASP": ["OD1", "OD2"],
    "BASP": ["OD1", "OD2"],
    "CASP": ["OD1", "OD2"],
    "A": ["OP1", "OP2", "PO1", "PO2"],
    "U": ["OP1", "OP2", "PO1", "PO2"],
    "G": ["OP1", "OP2", "PO1", "PO2"],
    "C": ["OP1", "OP2", "PO1", "PO2"],
    "PSU": ["OP1", "OP2", "PO1", "PO2"],
    "DA": ["OP1", "OP2", "PO1", "PO2"],
    "DT": ["OP1", "OP2", "PO1", "PO2"],
    "DG": ["OP1", "OP2", "PO1", "PO2"],
    "DC": ["OP1", "OP2", "PO1", "PO2"],
}

lone_pair_pi = {
    "A": ["O4'", "O2'", "O3'", "O5'", "N7", "N1", "N3"],
    "U": ["O2", "O4", "O4'", "O2'", "O3'", "O5'"],
    "G": ["O6", "N7", "O4'", "O2'", "O3'", "O5'", "N3"],
    "C": ["O2", "O4'", "O2'", "O3'", "O5'"],
    "PSU": ["O2", "O4", "O4'", "O2'", "O3'", "O5'"],
    "DA": ["O4'", "O2'", "O3'", "O5'", "N7", "N1", "N3"],
    "DT": ["O2", "O4", "O4'", "O2'", "O3'", "O5'"],
    "DG": ["O6", "N7", "O4'", "O2'", "O3'", "O5'", "N3"],
    "DC": ["O2", "O4'", "O2'", "O3'", "O5'"],
    "ALA": ["O"],
    "AALA": ["O"],
    "BALA": ["O"],
    "CALA": ["O"],
    "ASX": ["O"],
    "AASX": ["O"],
    "BASX": ["O"],
    "CASX": ["O"],
    "CYS": ["O", "SG"],
    "ACYS": ["O", "SG"],
    "BCYS": ["O", "SG"],
    "CCYS": ["O", "SG"],
    "ASP": ["O"],
    "AASP": ["O"],
    "BASP": ["O"],
    "CASP": ["O"],
    "GLU": ["O"],
    "AGLU": ["O"],
    "BGLU": ["O"],
    "CGLU": ["O"],
    "PHE": ["O"],
    "APHE": ["O"],
    "BPHE": ["O"],
    "CPHE": ["O"],
    "GLY": ["O"],
    "AGLY": ["O"],
    "BGLY": ["O"],
    "CGLY": ["O"],
    "HIS": ["O", "ND1", "NE2"],
    "AHIS": ["O", "ND1", "NE2"],
    "BHIS": ["O", "ND1", "NE2"],
    "CHIS": ["O", "ND1", "NE2"],
    "ILE": ["O"],
    "AILE": ["O"],
    "AILE": ["O"],
    "AILE": ["O"],
    "LYS": ["O"],
    "ALYS": ["O"],
    "BLYS": ["O"],
    "CLYS": ["O"],
    "LEU": ["O"],
    "ALEU": ["O"],
    "BLEU": ["O"],
    "CLEU": ["O"],
    "MET": ["O", "S", "SD"],
    "AMET": ["O", "S", "SD"],
    "BMET": ["O", "S", "SD"],
    "CMET": ["O", "S", "SD"],
    "ASN": ["O", "OD1"],
    "AASN": ["O", "OD1"],
    "BASN": ["O", "OD1"],
    "CASN": ["O", "OD1"],
    "PRO": ["O"],
    "APRO": ["O"],
    "BPRO": ["O"],
    "CPRO": ["O"],
    "GLN": ["O", "OE1"],
    "AGLN": ["O", "OE1"],
    "BGLN": ["O", "OE1"],
    "CGLN": ["O", "OE1"],
    "ARG": ["O"],
    "AARG": ["O"],
    "BARG": ["O"],
    "CARG": ["O"],
    "SER": ["O"],
    "ASER": ["O"],
    "BSER": ["O"],
    "CSER": ["O"],
    "THR": ["O"],
    "ATHR": ["O"],
    "BTHR": ["O"],
    "CTHR": ["O"],
    "SEC": ["O"],
    "VAL": ["O"],
    "AVAL": ["O"],
    "BVAL": ["O"],
    "CVAL": ["O"],
    "TRP": ["O"],
    "ATRP": ["O"],
    "BTRP": ["O"],
    "CTRP": ["O"],
    "XAA": ["O"],
    "TYR": ["O"],
    "ATYR": ["O"],
    "BTYR": ["O"],
    "CTYR": ["O"],
    "GLX": ["O"],
    "XLE": ["O"],
    "SEC": ["O"],
    "HIE": ["O"],
    "HSE": ["O"],
    "HID": ["O"],
    "HSD": ["O"],
    "HIP": ["O"],
    "HSP": ["O"],
    "HSP": ["O"],
    "ASH": ["O"],
    "GLH": ["O"],
    "CYX": ["O"],
    "CYM": ["O"],
    "LYN": ["O"],
    "TYM": ["O"],
}
# to be removed
# halogen_pi = {"BR": ["BR"], "CL": ["CL"], "F": ["F"], "I": ["I"]}

# to be removed
axis_definition_dictionary = {
    "A": [["N1", "C2"], "C6", 9],
    "G": [["N1", "C2"], "C6", 9],
    "U": [["N3"], "C4", 6],
    "C": [["N3"], "C4", 6],
    "PSU": [["N3"], "C2", 6],
    "DG": [["N1", "C2"], "C6", 9],
    "DA": [["N1", "C2"], "C6", 9],
    "DC": [["N3"], "C4", 6],
    "DT": [["N3"], "C4", 6],
    "TYR": [["CD1", "CE1"], "CZ", 6],
    "ATYR": [["CD1", "CE1"], "CZ", 6],
    "BTYR": [["CD1", "CE1"], "CZ", 6],
    "CTYR": [["CD1", "CE1"], "CZ", 6],
    "TRP": [["CZ3", "CH2"], "CZ2", 9],
    "ATRP": [["CZ3", "CH2"], "CZ2", 9],
    "BTRP": [["CZ3", "CH2"], "CZ2", 9],
    "CTRP": [["CZ3", "CH2"], "CZ2", 9],
    "HIS": [["CE1", "NE2"], "ND1", 5],
    "AHIS": [["CE1", "NE2"], "ND1", 5],
    "BHIS": [["CE1", "NE2"], "ND1", 5],
    "CHIS": [["CE1", "NE2"], "ND1", 5],
    "PHE": [["CD1", "CE1"], "CZ", 6],
    "APHE": [["CD1", "CE1"], "CZ", 6],
    "BPHE": [["CD1", "CE1"], "CZ", 6],
    "CPHE": [["CD1", "CE1"], "CZ", 6],
}

# THRESHOLDS = {6: [2.25, 2.25], 5: [1.57, 1.57], 9: [6.25, 2.25]}

AMINO_ACIDS = [
    "ALA",
    "ASX",
    "CYS",
    "ASP",
    "GLU",
    "PHE",
    "GLY",
    "HIS",
    "ILE",
    "LYS",
    "LEU",
    "MET",
    "ASN",
    "PRO",
    "GLN",
    "ARG",
    "SER",
    "THR",
    "SEC",
    "VAL",
    "TRP",
    "XAA",
    "TYR",
    "GLX",
    "XLE",
    "SEC",
    "HIE",
    "HSE",
    "HID",
    "HSD",
    "HIP",
    "HSP",
    "ASH",
    "GLH",
    "CYX",
    "CYM",
    "LYN",
    "TYM",
]

HALOGENS = {"F": [], "CL": [], "BR": [], "I": []}

RADII = {
    # this corresponds to bondii radious
    "H": 0.53,
    "O": 1.52, #1.52
    "F": 1.47,
    "CL": 1.75,
    "BR": 1.85,
    "I": 1.98,
    "N": 1.55,
    "S": 1.80,
    "P": 1.80,
    "C": 1.70,
}


HALOGEN_ELECTRONEGATIVE = {
    "A": ["O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N3", "N1"],
    "U": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2"],
    "G": ["O6", "N7", "O4'", "O3'", "O5'", "OP1", "OP2", "N3"],
    "C": ["O2", "O4'", "O3'", "O5'", "OP1", "OP2"],
    "PSU": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2"],
    "DA": ["O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N3", "N1"],
    "DT": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2"],
    "DG": ["O6", "N7", "O4'", "O3'", "O5'", "OP1", "OP2", "N3"],
    "DC": ["O2", "O4'", "O3'", "O5'", "OP1", "OP2"],
    "ALA": ["O"],
    "ASX": ["O"],
    "CYS": ["O"],
    "ASP": ["O", "OD1", "OD2"],
    "GLU": ["O", "OE1", "OE2"],
    "PHE": ["O"],
    "GLY": ["O"],
    "HIS": ["O"],
    "ILE": ["O"],
    "LYS": ["O"],
    "LEU": ["O"],
    "MET": ["O", "S"],
    "ASN": ["O", "OD1"],
    "PRO": ["O"],
    "GLN": ["O", "OE1"],
    "ARG": ["O"],
    "SER": ["O"],
    "THR": ["O"],
    "SEC": ["O"],
    "VAL": ["O"],
    "TRP": ["O"],
    "XAA": ["O"],
    "TYR": ["O"],
    "GLX": ["O"],
    "XLE": ["O"],
    "SEC": ["O"],
    "HIE": ["O"],
    "HSE": ["O"],
    "HID": ["O"],
    "HSD": ["O"],
    "HIP": ["O"],
    "HSP": ["O"],
    "ASH": ["O"],
    "GLH": ["O"],
    "CYX": ["O"],
    "CYM": ["O"],
    "LYN": ["O"],
    "TYM": ["O"],
}


WATER_MEDIATED = {  # HETATM is O
    "A": ["O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N6", "N1", "N3", "O2'"],
    "U": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2", "N3", "O2'"],
    "G": ["O6", "N7", "O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N1", "N3", "O2'"],
    "C": ["O2", "O4'", "O3'", "O5'", "OP1", "OP2", "N3", "N4", "O2'"],
    "PSU": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2", "N1", "N3", "O2'"],
    "DA": ["O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N6", "N1", "N3"],
    "DT": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2", "N3"],
    "DG": ["O6", "N7", "O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N1", "N3"],
    "DC": ["O2", "O4'", "O3'", "O5'", "OP1", "OP2", "N3", "N4"],
    "ALA": ["O", "OXT"],
    "ASX": ["O"],
    "CYS": ["O", "OXT", "SG"],
    "ASP": ["O", "OD1", "OD2", "OXT"],
    "GLU": ["O", "OE1", "OE2", "OXT"],
    "PHE": ["O", "OXT"],
    "GLY": ["O", "OXT"],
    "HIS": ["O", "OXT", "ND1", "CE1", "NE2", "CD2"],
    "ILE": ["O", "OXT"],
    "LYS": ["O", "OXT"],
    "LEU": ["O", "OXT"],
    "MET": ["O", "S", "OXT", "SD"],
    "ASN": ["O", "OD1", "OXT", "ND2"],
    "PRO": ["O", "OXT"],
    "GLN": ["O", "OE1", "OXT", "NE2"],
    "ARG": ["O", "OXT"],
    "SER": ["O", "OXT", "OG"],
    "THR": ["O", "OXT", "OG1"],
    "SEC": ["O"],
    "VAL": ["O", "OXT"],
    "TRP": ["O", "OXT"],
    "XAA": ["O"],
    "TYR": ["O", "OXT", "OH"],
    "GLX": ["O"],
    "XLE": ["O"],
    "SEC": ["O"],
    "HIE": ["O"],
    "HSE": ["O"],
    "HID": ["O"],
    "HSD": ["O"],
    "HIP": ["O"],
    "HSP": ["O"],
    "ASH": ["O"],
    "GLH": ["O"],
    "CYX": ["O"],
    "CYM": ["O"],
    "LYN": ["O"],
    "TYM": ["O"],
}


METAL_MEDIATED = {
    "A": ["O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N1", "N3", "O2'"],
    "U": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2", "N3", "O2'"],
    "G": ["O6", "N7", "O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N1", "N3", "O2'"],
    "C": ["O2", "O4'", "O3'", "O5'", "OP1", "OP2", "N3", "O2'"],
    "PSU": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2", "N1", "N3", "O2'"],
    "DA": ["O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N1", "N3"],
    "DT": ["O2", "O4", "O4'", "O3'", "O5'", "OP1", "OP2", "N3"],
    "DG": ["O6", "N7", "O4'", "O3'", "O5'", "OP1", "OP2", "N7", "N1", "N3"],
    "DC": ["O2", "O4'", "O3'", "O5'", "OP1", "OP2", "N3"],
    "ALA": ["O", "OXT"],
    "AALA": ["O", "OXT"],
    "BALA": ["O", "OXT"],
    "CALA": ["O", "OXT"],
    "ASX": ["O"],
    "AASX": ["O"],
    "BASX": ["O"],
    "CASX": ["O"],
    "CYS": ["O", "OXT", "SG"],
    "ACYS": ["O", "OXT", "SG"],
    "BCYS": ["O", "OXT", "SG"],
    "CCYS": ["O", "OXT", "SG"],
    "ASP": ["O", "OD1", "OD2", "OXT"],
    "AASP": ["O", "OD1", "OD2", "OXT"],
    "BASP": ["O", "OD1", "OD2", "OXT"],
    "CASP": ["O", "OD1", "OD2", "OXT"],
    "GLU": ["O", "OE1", "OE2", "OXT"],
    "AGLU": ["O", "OE1", "OE2", "OXT"],
    "BGLU": ["O", "OE1", "OE2", "OXT"],
    "CGLU": ["O", "OE1", "OE2", "OXT"],
    "PHE": ["O", "OXT"],
    "APHE": ["O", "OXT"],
    "BPHE": ["O", "OXT"],
    "CPHE": ["O", "OXT"],
    "GLY": ["O", "OXT"],
    "AGLY": ["O", "OXT"],
    "BGLY": ["O", "OXT"],
    "CGLY": ["O", "OXT"],
    "HIS": ["O", "OXT", "ND1", "CE1", "NE2", "CD2", "NE1"],
    "AHIS": ["O", "OXT", "ND1", "CE1", "NE2", "CD2", "NE1"],
    "BHIS": ["O", "OXT", "ND1", "CE1", "NE2", "CD2", "NE1"],
    "BHIS": ["O", "OXT", "ND1", "CE1", "NE2", "CD2", "NE1"],
    "ILE": ["O", "OXT"],
    "AILE": ["O", "OXT"],
    "BILE": ["O", "OXT"],
    "CILE": ["O", "OXT"],
    "LYS": ["O", "OXT"],
    "ALYS": ["O", "OXT"],
    "BLYS": ["O", "OXT"],
    "CLYS": ["O", "OXT"],
    "LEU": ["O", "OXT"],
    "ALEU": ["O", "OXT"],
    "BLEU": ["O", "OXT"],
    "CLEU": ["O", "OXT"],
    "MET": ["O", "S", "OXT", "SD"],
    "AMET": ["O", "S", "OXT", "SD"],
    "BMET": ["O", "S", "OXT", "SD"],
    "CMET": ["O", "S", "OXT", "SD"],
    "ASN": ["O", "OD1", "OXT", "ND2"],
    "AASN": ["O", "OD1", "OXT", "ND2"],
    "BASN": ["O", "OD1", "OXT", "ND2"],
    "CASN": ["O", "OD1", "OXT", "ND2"],
    "PRO": ["O", "OXT"],
    "APRO": ["O", "OXT"],
    "BPRO": ["O", "OXT"],
    "CPRO": ["O", "OXT"],
    "GLN": ["O", "OE1", "OXT", "NE2"],
    "AGLN": ["O", "OE1", "OXT", "NE2"],
    "BGLN": ["O", "OE1", "OXT", "NE2"],
    "CGLN": ["O", "OE1", "OXT", "NE2"],
    "ARG": ["O", "OXT"],
    "AARG": ["O", "OXT"],
    "BARG": ["O", "OXT"],
    "CARG": ["O", "OXT"],
    "SER": ["O", "OXT", "OG"],
    "ASER": ["O", "OXT", "OG"],
    "BSER": ["O", "OXT", "OG"],
    "CSER": ["O", "OXT", "OG"],
    "THR": ["O", "OXT", "OG1"],
    "ATHR": ["O", "OXT", "OG1"],
    "BTHR": ["O", "OXT", "OG1"],
    "CTHR": ["O", "OXT", "OG1"],
    "VAL": ["O", "OXT"],
    "AVAL": ["O", "OXT"],
    "BVAL": ["O", "OXT"],
    "CVAL": ["O", "OXT"],
    "TRP": ["O", "OXT"],
    "ATRP": ["O", "OXT"],
    "BTRP": ["O", "OXT"],
    "CTRP": ["O", "OXT"],
    "XAA": ["O"],
    "TYR": ["O", "OXT", "OH"],
    "ATYR": ["O", "OXT", "OH"],
    "BTYR": ["O", "OXT", "OH"],
    "CTYR": ["O", "OXT", "OH"],
    "GLX": ["O"],
    "XLE": ["O"],
    "SEC": ["O"],
    "HIE": ["O"],
    "HSE": ["O"],
    "HID": ["O"],
    "HSD": ["O"],
    "HIP": ["O"],
    "HSP": ["O"],
    "ASH": ["O"],
    "GLH": ["O"],
    "CYX": ["O"],
    "CYM": ["O"],
    "LYN": ["O"],
    "TYM": ["O"],
}

"""Adding modifications to all the dictionaries"""
for mod in Modified_a:
    axis_definition_dictionary[mod] = axis_definition_dictionary["A"]
    anion_pi[mod] = anion_pi["A"]
    lone_pair_pi[mod] = lone_pair_pi["A"]
    HALOGEN_ELECTRONEGATIVE[mod] = HALOGEN_ELECTRONEGATIVE["A"]
    WATER_MEDIATED[mod] = WATER_MEDIATED["A"]
    METAL_MEDIATED[mod] = METAL_MEDIATED["A"]
for mod in Modified_g:
    axis_definition_dictionary[mod] = axis_definition_dictionary["G"]
    anion_pi[mod] = anion_pi["G"]
    lone_pair_pi[mod] = lone_pair_pi["G"]
    HALOGEN_ELECTRONEGATIVE[mod] = HALOGEN_ELECTRONEGATIVE["G"]
    WATER_MEDIATED[mod] = WATER_MEDIATED["G"]
    METAL_MEDIATED[mod] = METAL_MEDIATED["G"]
for mod in Modified_c:
    axis_definition_dictionary[mod] = axis_definition_dictionary["C"]
    anion_pi[mod] = anion_pi["C"]
    lone_pair_pi[mod] = lone_pair_pi["C"]
    HALOGEN_ELECTRONEGATIVE[mod] = HALOGEN_ELECTRONEGATIVE["C"]
    WATER_MEDIATED[mod] = WATER_MEDIATED["C"]
    METAL_MEDIATED[mod] = METAL_MEDIATED["C"]
for mod in Modified_u:
    axis_definition_dictionary[mod] = axis_definition_dictionary["U"]
    anion_pi[mod] = anion_pi["U"]
    lone_pair_pi[mod] = lone_pair_pi["U"]
    HALOGEN_ELECTRONEGATIVE[mod] = HALOGEN_ELECTRONEGATIVE["U"]
    WATER_MEDIATED[mod] = WATER_MEDIATED["U"]
    METAL_MEDIATED[mod] = METAL_MEDIATED["U"]

# all will be found in HETATM
METALS = set(
    [
        "3CO",
        "LI",
        "BE",
        "NA",
        "MG",
        "AL",
        "K",
        "CA",
        "SC",
        "TI",
        "V",
        "CR",
        "MN",
        "FE",
        "CO",
        "NI",
        "CU",
        "ZN",
        "GA",
        "RB",
        "SR",
        "Y",
        "ZR",
        "NB",
        "MO",
        "TC",
        "RU",
        "RH",
        "PD",
        "AG",
        "CD",
        "IN",
        "SN",
        "CS",
        "BA",
        "LA",
        "CE",
        "PR",
        "ND",
        "PM",
        "SM",
        "EU",
        "GD",
        "TB",
        "DY",
        "HO",
        "ER",
        "TM",
        "YB",
        "LU",
        "HF",
        "TA",
        "W",
        "RE",
        "OS",
        "IR",
        "PT",
        "AU",
        "HG",
        "TL",
        "PB",
        "BI",
        "PO",
        "FR",
        "RA",
        "AC",
        "TH",
        "PA",
        "NP",
        "PU",
        "AM",
        "CM",
        "BK",
        "CF",
    ]
)

METAL_DISTANCES = {
    "3CO": 3.2,
    "AG": 3.2,
    "BI": 3.2,
    "RE": 3.2,
    "Y": 3.2,
    "DY": 3.2,
    "EU": 3.2,
    "HO": 3.2,
    "HF": 3.2,
    "PU": 3.2,
    "HG": 3.2,
    "ND": 3.2,
    "CS": 3.2,
    "PA": 3.2,
    "V": 3.2,
    "IR": 3.2,
    "LU": 3.2,
    "CD": 3.2,
    "RB": 3.2,
    "PR": 3.2,
    "GA": 3.2,
    "ER": 3.2,
    "MO": 3.2,
    "AC": 3.2,
    "CF": 3.2,
    "CU": 3.2,
    "CO": 3.2,
    "NB": 3.2,
    "PB": 3.2,
    "SR": 3.2,
    "ZN": 3.2,
    "TH": 3.2,
    "TA": 3.2,
    "LA": 3.2,
    "NP": 3.2,
    "GD": 3.2,
    "RH": 3.2,
    "MN": 3.2,
    "AU": 3.2,
    "RA": 3.2,
    "BK": 3.2,
    "NA": 3.2,
    "TC": 3.2,
    "PM": 3.2,
    "TL": 3.2,
    "LI": 3.2,
    "SM": 3.2,
    "W": 3.2,
    "MG": 3.2,
    "NI": 3.2,
    "TB": 3.2,
    "SC": 3.2,
    "FE": 3.2,
    "K": 3.2,
    "OS": 3.2,
    "TI": 3.2,
    "PD": 3.2,
    "TM": 3.2,
    "YB": 3.2,
    "PO": 3.2,
    "CR": 3.2,
    "ZR": 3.2,
    "IN": 3.2,
    "SN": 3.2,
    "CE": 3.2,
    "FR": 3.2,
    "AM": 3.2,
    "BA": 3.2,
    "AL": 3.2,
    "CA": 3.2,
    "RU": 3.2,
    "PT": 3.2,
    "BE": 3.2,
    "CM": 3.2,
    "U": 3.2,
}

ACCEPTOR_ATOMS = lone_pair_pi.copy()
for key, value in anion_pi.items():
    if key in ACCEPTOR_ATOMS:
        ACCEPTOR_ATOMS[key] = list(set(ACCEPTOR_ATOMS[key] + value))

WEAK_H_BONDS = {
    "GLY": {"CA": ["HA2", "HA3"]},
    "AGLY": {"CA": ["HA2", "HA3"]},
    "BGLY": {"CA": ["HA2", "HA3"]},
    "CGLY": {"CA": ["HA2", "HA3"]},
    "ALA": {"CA": ["HA"], "CB": ["HB1", "HB2", "HB3"]},
    "AALA": {"CA": ["HA"], "CB": ["HB1", "HB2", "HB3"]},
    "BALA": {"CA": ["HA"], "CB": ["HB1", "HB2", "HB3"]},
    "CALA": {"CA": ["HA"], "CB": ["HB1", "HB2", "HB3"]},
    "VAL": {
        "CA": ["HA"],
        "CB": ["HB"],
        "CG1": ["HG11", "HG12", "HG13"],
        "CG2": ["HG21", "HG22", "HG23"],
    },
    "AVAL": {
        "CA": ["HA"],
        "CB": ["HB"],
        "CG1": ["HG11", "HG12", "HG13"],
        "CG2": ["HG21", "HG22", "HG23"],
    },
    "BVAL": {
        "CA": ["HA"],
        "CB": ["HB"],
        "CG1": ["HG11", "HG12", "HG13"],
        "CG2": ["HG21", "HG22", "HG23"],
    },
    "CVAL": {
        "CA": ["HA"],
        "CB": ["HB"],
        "CG1": ["HG11", "HG12", "HG13"],
        "CG2": ["HG21", "HG22", "HG23"],
    },
    "CYS": {"CA": ["HA"], "CB": ["HB2", "HB3"]},
    "ACYS": {"CA": ["HA"], "CB": ["HB2", "HB3"]},
    "BCYS": {"CA": ["HA"], "CB": ["HB2", "HB3"]},
    "CCYS": {"CA": ["HA"], "CB": ["HB2", "HB3"]},
    "PRO": {
        "CA": ["HA"],
        "CD": ["HD2", "HD3"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "APRO": {
        "CA": ["HA"],
        "CD": ["HD2", "HD3"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "BPRO": {
        "CA": ["HA"],
        "CD": ["HD2", "HD3"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "CPRO": {
        "CA": ["HA"],
        "CD": ["HD2", "HD3"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "LEU": {
        "CA": ["HA"],
        "CG": ["HG"],
        "CB": ["HB2", "HB3"],
        "CD1": ["HD11", "HD12", "HD13"],
        "CD2": ["HD21", "HD22", "HD23"],
    },
    "CLEU": {
        "CA": ["HA"],
        "CG": ["HG"],
        "CB": ["HB2", "HB3"],
        "CD1": ["HD11", "HD12", "HD13"],
        "CD2": ["HD21", "HD22", "HD23"],
    },
    "ALEU": {
        "CA": ["HA"],
        "CG": ["HG"],
        "CB": ["HB2", "HB3"],
        "CD1": ["HD11", "HD12", "HD13"],
        "CD2": ["HD21", "HD22", "HD23"],
    },
    "BLEU": {
        "CA": ["HA"],
        "CG": ["HG"],
        "CB": ["HB2", "HB3"],
        "CD1": ["HD11", "HD12", "HD13"],
        "CD2": ["HD21", "HD22", "HD23"],
    },
    "ILE": {
        "CA": ["HA"],
        "CB": ["HB"],
        "CG1": ["HG12", "HG13"],
        "CG2": ["HG21", "HG22", "HG23"],
        "CD1": ["HD11", "HD12", "HD13"],
    },
    "AILE": {
        "CA": ["HA"],
        "CB": ["HB"],
        "CG1": ["HG12", "HG13"],
        "CG2": ["HG21", "HG22", "HG23"],
        "CD1": ["HD11", "HD12", "HD13"],
    },
    "BILE": {
        "CA": ["HA"],
        "CB": ["HB"],
        "CG1": ["HG12", "HG13"],
        "CG2": ["HG21", "HG22", "HG23"],
        "CD1": ["HD11", "HD12", "HD13"],
    },
    "CILE": {
        "CA": ["HA"],
        "CB": ["HB"],
        "CG1": ["HG12", "HG13"],
        "CG2": ["HG21", "HG22", "HG23"],
        "CD1": ["HD11", "HD12", "HD13"],
    },
    "MET": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CE": ["HE1", "HE2", "HE3"],
    },
    "AMET": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CE": ["HE1", "HE2", "HE3"],
    },
    "BMET": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CE": ["HE1", "HE2", "HE3"],
    },
    "CMET": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CE": ["HE1", "HE2", "HE3"],
    },
    "TRP": {
        "CA": ["HA"],
        "CD1": ["HD1"],
        "CZ2": ["HZ2"],
        "CH2": ["HH2"],
        "CE3": ["HE3"],
        "CZ3": ["HZ3"],
        "CB": ["HB2", "HB3"],
    },
    "ATRP": {
        "CA": ["HA"],
        "CD1": ["HD1"],
        "CZ2": ["HZ2"],
        "CH2": ["HH2"],
        "CE3": ["HE3"],
        "CZ3": ["HZ3"],
        "CB": ["HB2", "HB3"],
    },
    "BTRP": {
        "CA": ["HA"],
        "CD1": ["HD1"],
        "CZ2": ["HZ2"],
        "CH2": ["HH2"],
        "CE3": ["HE3"],
        "CZ3": ["HZ3"],
        "CB": ["HB2", "HB3"],
    },
    "CTRP": {
        "CA": ["HA"],
        "CD1": ["HD1"],
        "CZ2": ["HZ2"],
        "CH2": ["HH2"],
        "CE3": ["HE3"],
        "CZ3": ["HZ3"],
        "CB": ["HB2", "HB3"],
    },
    "PHE": {
        "CA": ["HA"],
        "CD1": ["HD1"],
        "CE1": ["HE1"],
        "CD2": ["HD2"],
        "CE2": ["HE2"],
        "CZ": ["HZ"],
        "CB": ["HB2", "HB3"],
    },
    "APHE": {
        "CA": ["HA"],
        "CD1": ["HD1"],
        "CE1": ["HE1"],
        "CD2": ["HD2"],
        "CE2": ["HE2"],
        "CZ": ["HZ"],
        "CB": ["HB2", "HB3"],
    },
    "BPHE": {
        "CA": ["HA"],
        "CD1": ["HD1"],
        "CE1": ["HE1"],
        "CD2": ["HD2"],
        "CE2": ["HE2"],
        "CZ": ["HZ"],
        "CB": ["HB2", "HB3"],
    },
    "CPHE": {
        "CA": ["HA"],
        "CD1": ["HD1"],
        "CE1": ["HE1"],
        "CD2": ["HD2"],
        "CE2": ["HE2"],
        "CZ": ["HZ"],
        "CB": ["HB2", "HB3"],
    },
    "SER": {"CA": ["HA"], "CB": ["HB2", "HB3"]},
    "ASER": {"CA": ["HA"], "CB": ["HB2", "HB3"]},
    "BSER": {"CA": ["HA"], "CB": ["HB2", "HB3"]},
    "CSER": {"CA": ["HA"], "CB": ["HB2", "HB3"]},
    "THR": {"CA": ["HA"], "CB": ["HB"], "CG2": ["HG21", "HG22", "HG23"]},
    "ATHR": {"CA": ["HA"], "CB": ["HB"], "CG2": ["HG21", "HG22", "HG23"]},
    "BTHR": {"CA": ["HA"], "CB": ["HB"], "CG2": ["HG21", "HG22", "HG23"]},
    "CTHR": {"CA": ["HA"], "CB": ["HB"], "CG2": ["HG21", "HG22", "HG23"]},
    "TYR": {
        "CA": ["HA"],
        "CD1": ["HD1"],
        "CE1": ["HE1"],
        "CD2": ["HD2"],
        "CE2": ["HE2"],
        "CZ": ["HH"],
        "CB": ["HB2", "HB3"],
    },
    "ATYR": {
        "CA": ["HA"],
        "CD1": ["HD1"],
        "CE1": ["HE1"],
        "CD2": ["HD2"],
        "CE2": ["HE2"],
        "CZ": ["HH"],
        "CB": ["HB2", "HB3"],
    },
    "BTYR": {
        "CA": ["HA"],
        "CD1": ["HD1"],
        "CE1": ["HE1"],
        "CD2": ["HD2"],
        "CE2": ["HE2"],
        "CZ": ["HH"],
        "CB": ["HB2", "HB3"],
    },
    "CTYR": {
        "CA": ["HA"],
        "CD1": ["HD1"],
        "CE1": ["HE1"],
        "CD2": ["HD2"],
        "CE2": ["HE2"],
        "CZ": ["HH"],
        "CB": ["HB2", "HB3"],
    },
    "ASN": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
    },
    "AASN": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
    },
    "BASN": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
    },
    "CASN": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
    },
    "GLN": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "AGLN": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "BGLN": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "CGLN": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "LYS": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CD": ["HD2", "HD3"],
        "CE": ["HE2", "HE3"],
    },
    "ALYS": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CD": ["HD2", "HD3"],
        "CE": ["HE2", "HE3"],
    },
    "BLYS": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CD": ["HD2", "HD3"],
        "CE": ["HE2", "HE3"],
    },
    "CLYS": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CD": ["HD2", "HD3"],
        "CE": ["HE2", "HE3"],
    },
    "ARG": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CD": ["HD2", "HD3"],
    },
    "AARG": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CD": ["HD2", "HD3"],
    },
    "BARG": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CD": ["HD2", "HD3"],
    },
    "CARG": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CD": ["HD2", "HD3"],
    },
    "HIS": {
        "CA": ["HA"],
        "CE1": ["HE1"],
        "CD2": ["HD2"],
        "CB": ["HB2", "HB3"],
    },
    "CHIS": {
        "CA": ["HA"],
        "CE1": ["HE1"],
        "CD2": ["HD2"],
        "CB": ["HB2", "HB3"],
    },
    "AHIS": {
        "CA": ["HA"],
        "CE1": ["HE1"],
        "CD2": ["HD2"],
        "CB": ["HB2", "HB3"],
    },
    "BHIS": {
        "CA": ["HA"],
        "CE1": ["HE1"],
        "CD2": ["HD2"],
        "CB": ["HB2", "HB3"],
    },
    "ASP": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
    },
    "AASP": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
    },
    "BASP": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
    },
    "CASP": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
    },
    "GLU": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "AGLU": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "BGLU": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "CGLU": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "DA": {
        "C1'": ["H1'"],
        "C2'": ["H2'"],
        "C3'": ["H3'"],
        "C4'": ["H4'"],
        "C5'": ["H5'", "H5''"],
        "C8": ["H8"],
        "C2": ["H2"],
    },
    "DT": {
        "C1'": ["H1'"],
        "C2'": ["H2'"],
        "C3'": ["H3'"],
        "C4'": ["H4'"],
        "C5'": ["H5'", "H5''"],
        "C6": ["H6"],
        "C7": ["H71", "H72", "H73"],
    },
    "DG": {
        "C1'": ["H1'"],
        "C2'": ["H2'"],
        "C3'": ["H3'"],
        "C4'": ["H4'"],
        "C5'": ["H5'", "H5''"],
        "C8": ["H8"],
    },
    "DC": {
        "C1'": ["H1'"],
        "C2'": ["H2'"],
        "C3'": ["H3'"],
        "C4'": ["H4'"],
        "C5'": ["H5'", "H5''"],
        "C5": ["H5"],
        "C6": ["H6"],
    },
    "A": {
        "C1'": ["H1'"],
        "C2'": ["H2'"],
        "C3'": ["H3'"],
        "C4'": ["H4'"],
        "C5'": ["H5'", "H5''"],
        "C8": ["H8"],
        "C2": ["H2"],
    },
    "U": {
        "C1'": ["H1'"],
        "C2'": ["H2'"],
        "C3'": ["H3'"],
        "C4'": ["H4'"],
        "C5'": ["H5'", "H5''"],
        "C6": ["H6"],
        "C5": ["H5"],
    },
    "G": {
        "C1'": ["H1'"],
        "C2'": ["H2'"],
        "C3'": ["H3'"],
        "C4'": ["H4'"],
        "C5'": ["H5'", "H5''"],
        "C8": ["H8"],
    },
    "C": {
        "C1'": ["H1'"],
        "C2'": ["H2'"],
        "C3'": ["H3'"],
        "C4'": ["H4'"],
        "C5'": ["H5'", "H5''"],
        "C5": ["H5"],
        "C6": ["H6"],
    },
}

SALT_BRIDGE_CONDITION1 = {
    "side1": {"LYS": ["NZ"], "ARG": ["NH1", "NH2"], "HIP": ["ND1", "NE2"]},
    "side2": {"ASP": ["OD1", "OD2"], "GLU": ["OE1", "OE2"], "Y1P": ["O1P", "O2P", "O3P"] , "PTR": ["O1P", "O2P", "O3P"]},
}
SALT_BRIDGE_CONDITION2 = {
    "side1": {"LYS": ["NZ"], "ARG": ["NH1", "NH2"]},
    "side2": ["A", "U", "G", "C", "DA", "DG", "DC", "DT", "PSU"],
    "allowed_atoms_side2": ["OP1", "OP2"],
}

C_H_PI = {
    "GLY": {"CA": ["HA2", "HA3"]},
    "AGLY": {"CA": ["HA2", "HA3"]},
    "BGLY": {"CA": ["HA2", "HA3"]},
    "CGLY": {"CA": ["HA2", "HA3"]},
    "ALA": {"CA": ["HA"], "CB": ["HB1", "HB2", "HB3"]},
    "AALA": {"CA": ["HA"], "CB": ["HB1", "HB2", "HB3"]},
    "BALA": {"CA": ["HA"], "CB": ["HB1", "HB2", "HB3"]},
    "CALA": {"CA": ["HA"], "CB": ["HB1", "HB2", "HB3"]},
    "VAL": {
        "CA": ["HA"],
        "CB": ["HB"],
        "CG1": ["HG11", "HG12", "HG13"],
        "CG2": ["HG21", "HG22", "HG23"],
    },
    "AVAL": {
        "CA": ["HA"],
        "CB": ["HB"],
        "CG1": ["HG11", "HG12", "HG13"],
        "CG2": ["HG21", "HG22", "HG23"],
    },
    "BVAL": {
        "CA": ["HA"],
        "CB": ["HB"],
        "CG1": ["HG11", "HG12", "HG13"],
        "CG2": ["HG21", "HG22", "HG23"],
    },
    "CVAL": {
        "CA": ["HA"],
        "CB": ["HB"],
        "CG1": ["HG11", "HG12", "HG13"],
        "CG2": ["HG21", "HG22", "HG23"],
    },
    "CYS": {"CA": ["HA"], "CB": ["HB2", "HB3"]},
    "ACYS": {"CA": ["HA"], "CB": ["HB2", "HB3"]},
    "BCYS": {"CA": ["HA"], "CB": ["HB2", "HB3"]},
    "CCYS": {"CA": ["HA"], "CB": ["HB2", "HB3"]},
    "PRO": {
        "CA": ["HA"],
        "CD": ["HD2", "HD3"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "APRO": {
        "CA": ["HA"],
        "CD": ["HD2", "HD3"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "BPRO": {
        "CA": ["HA"],
        "CD": ["HD2", "HD3"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "CPRO": {
        "CA": ["HA"],
        "CD": ["HD2", "HD3"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "LEU": {
        "CA": ["HA"],
        "CG": ["HG"],
        "CB": ["HB2", "HB3"],
        "CD1": ["HD11", "HD12", "HD13"],
        "CD2": ["HD21", "HD22", "HD23"],
    },
    "CLEU": {
        "CA": ["HA"],
        "CG": ["HG"],
        "CB": ["HB2", "HB3"],
        "CD1": ["HD11", "HD12", "HD13"],
        "CD2": ["HD21", "HD22", "HD23"],
    },
    "ALEU": {
        "CA": ["HA"],
        "CG": ["HG"],
        "CB": ["HB2", "HB3"],
        "CD1": ["HD11", "HD12", "HD13"],
        "CD2": ["HD21", "HD22", "HD23"],
    },
    "BLEU": {
        "CA": ["HA"],
        "CG": ["HG"],
        "CB": ["HB2", "HB3"],
        "CD1": ["HD11", "HD12", "HD13"],
        "CD2": ["HD21", "HD22", "HD23"],
    },
    "ILE": {
        "CA": ["HA"],
        "CB": ["HB"],
        "CG1": ["HG12", "HG13"],
        "CG2": ["HG21", "HG22", "HG23"],
        "CD1": ["HD11", "HD12", "HD13"],
    },
    "AILE": {
        "CA": ["HA"],
        "CB": ["HB"],
        "CG1": ["HG12", "HG13"],
        "CG2": ["HG21", "HG22", "HG23"],
        "CD1": ["HD11", "HD12", "HD13"],
    },
    "BILE": {
        "CA": ["HA"],
        "CB": ["HB"],
        "CG1": ["HG12", "HG13"],
        "CG2": ["HG21", "HG22", "HG23"],
        "CD1": ["HD11", "HD12", "HD13"],
    },
    "CILE": {
        "CA": ["HA"],
        "CB": ["HB"],
        "CG1": ["HG12", "HG13"],
        "CG2": ["HG21", "HG22", "HG23"],
        "CD1": ["HD11", "HD12", "HD13"],
    },
    "MET": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CE": ["HE1", "HE2", "HE3"],
    },
    "AMET": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CE": ["HE1", "HE2", "HE3"],
    },
    "BMET": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CE": ["HE1", "HE2", "HE3"],
    },
    "CMET": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CE": ["HE1", "HE2", "HE3"],
    },
    "TRP": {
        "CA": ["HA"],
        # removed
        "CB": ["HB2", "HB3"],
    },
    "ATRP": {
        "CA": ["HA"],
        # removed
        "CB": ["HB2", "HB3"],
    },
    "BTRP": {
        "CA": ["HA"],
        # removed
        "CB": ["HB2", "HB3"],
    },
    "CTRP": {
        "CA": ["HA"],
        # removed
        "CB": ["HB2", "HB3"],
    },
    "PHE": {
        "CA": ["HA"],
        # removed
        "CB": ["HB2", "HB3"],
    },
    "APHE": {
        "CA": ["HA"],
        # removed
        "CB": ["HB2", "HB3"],
    },
    "BPHE": {
        "CA": ["HA"],
        # removed
        "CB": ["HB2", "HB3"],
    },
    "CPHE": {
        "CA": ["HA"],
        # removed
        "CB": ["HB2", "HB3"],
    },
    "SER": {"CA": ["HA"], "CB": ["HB2", "HB3"]},
    "ASER": {"CA": ["HA"], "CB": ["HB2", "HB3"]},
    "BSER": {"CA": ["HA"], "CB": ["HB2", "HB3"]},
    "CSER": {"CA": ["HA"], "CB": ["HB2", "HB3"]},
    "THR": {"CA": ["HA"], "CB": ["HB"], "CG2": ["HG21", "HG22", "HG23"]},
    "ATHR": {"CA": ["HA"], "CB": ["HB"], "CG2": ["HG21", "HG22", "HG23"]},
    "BTHR": {"CA": ["HA"], "CB": ["HB"], "CG2": ["HG21", "HG22", "HG23"]},
    "CTHR": {"CA": ["HA"], "CB": ["HB"], "CG2": ["HG21", "HG22", "HG23"]},
    "TYR": {
        "CA": ["HA"],
        # removed
        "CB": ["HB2", "HB3"],
    },
    "ATYR": {
        "CA": ["HA"],
        # removed
        "CB": ["HB2", "HB3"],
    },
    "BTYR": {
        "CA": ["HA"],
        # removed
        "CB": ["HB2", "HB3"],
    },
    "CTYR": {
        "CA": ["HA"],
        # removed
        "CB": ["HB2", "HB3"],
    },
    "ASN": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
    },
    "AASN": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
    },
    "BASN": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
    },
    "CASN": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
    },
    "GLN": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "AGLN": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "BGLN": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "CGLN": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "LYS": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CD": ["HD2", "HD3"],
        "CE": ["HE2", "HE3"],
    },
    "ALYS": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CD": ["HD2", "HD3"],
        "CE": ["HE2", "HE3"],
    },
    "BLYS": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CD": ["HD2", "HD3"],
        "CE": ["HE2", "HE3"],
    },
    "CLYS": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CD": ["HD2", "HD3"],
        "CE": ["HE2", "HE3"],
    },
    "ARG": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CD": ["HD2", "HD3"],
    },
    "AARG": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CD": ["HD2", "HD3"],
    },
    "BARG": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CD": ["HD2", "HD3"],
    },
    "CARG": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
        "CD": ["HD2", "HD3"],
    },
    "HIS": {
        "CA": ["HA"],
        # removed
    },
    "CHIS": {
        "CA": ["HA"],
        # removed
    },
    "AHIS": {
        "CA": ["HA"],
        # removed
    },
    "BHIS": {
        "CA": ["HA"],
        # removed
    },
    "ASP": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
    },
    "AASP": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
    },
    "BASP": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
    },
    "CASP": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
    },
    "GLU": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "AGLU": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "BGLU": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "CGLU": {
        "CA": ["HA"],
        "CB": ["HB2", "HB3"],
        "CG": ["HG2", "HG3"],
    },
    "DA": {
        "C1'": ["H1'"],
        "C2'": ["H2'"],
        "C3'": ["H3'"],
        "C4'": ["H4'"],
        "C5'": ["H5'", "H5''"],
        "C8": ["H8"],
        "C2": ["H2"],
    },
    "DT": {
        "C1'": ["H1'"],
        "C2'": ["H2'"],
        "C3'": ["H3'"],
        "C4'": ["H4'"],
        "C5'": ["H5'", "H5''"],
        "C6": ["H6"],
        "C7": ["H71", "H72", "H73"],
    },
    "DG": {
        "C1'": ["H1'"],
        "C2'": ["H2'"],
        "C3'": ["H3'"],
        "C4'": ["H4'"],
        "C5'": ["H5'", "H5''"],
        "C8": ["H8"],
    },
    "DC": {
        "C1'": ["H1'"],
        "C2'": ["H2'"],
        "C3'": ["H3'"],
        "C4'": ["H4'"],
        "C5'": ["H5'", "H5''"],
        "C5": ["H5"],
        "C6": ["H6"],
    },
    "A": {
        "C1'": ["H1'"],
        "C2'": ["H2'"],
        "C3'": ["H3'"],
        "C4'": ["H4'"],
        "C5'": ["H5'", "H5''"],
        "C8": ["H8"],
        "C2": ["H2"],
    },
    "U": {
        "C1'": ["H1'"],
        "C2'": ["H2'"],
        "C3'": ["H3'"],
        "C4'": ["H4'"],
        "C5'": ["H5'", "H5''"],
        "C6": ["H6"],
        "C5": ["H5"],
    },
    "G": {
        "C1'": ["H1'"],
        "C2'": ["H2'"],
        "C3'": ["H3'"],
        "C4'": ["H4'"],
        "C5'": ["H5'", "H5''"],
        "C8": ["H8"],
    },
    "C": {
        "C1'": ["H1'"],
        "C2'": ["H2'"],
        "C3'": ["H3'"],
        "C4'": ["H4'"],
        "C5'": ["H5'", "H5''"],
        "C5": ["H5"],
        "C6": ["H6"],
    },
}


NSOH_PI = {
    "GLY": {"N": ["H"]},
    "AGLY": {"N": ["H"]},
    "BGLY": {"N": ["H"]},
    "CGLY": {"N": ["H"]},
    "ALA": {"N": ["H"]},
    "AALA": {"N": ["H"]},
    "BALA": {"N": ["H"]},
    "CALA": {"N": ["H"]},
    "VAL": {"N": ["H"]},
    "AVAL": {"N": ["H"]},
    "BVAL": {"N": ["H"]},
    "CVAL": {"N": ["H"]},
    "CYS": {
        "SG": ["HG"],
        "N": ["H"],
    },
    "ACYS": {
        "SG": ["HG"],
        "N": ["H"],
    },
    "BCYS": {
        "SG": ["HG"],
        "N": ["H"],
    },
    "CCYS": {
        "SG": ["HG"],
        "N": ["H"],
    },
    "PRO": {"N": ["H"]},
    "APRO": {"N": ["H"]},
    "BPRO": {"N": ["H"]},
    "CPRO": {"N": ["H"]},
    "LEU": {"N": ["H"]},
    "ALEU": {"N": ["H"]},
    "BLEU": {"N": ["H"]},
    "CLEU": {"N": ["H"]},
    "ILE": {"N": ["H"]},
    "AILE": {"N": ["H"]},
    "BILE": {"N": ["H"]},
    "CILE": {"N": ["H"]},
    "MET": {"N": ["H"]},
    "AMET": {"N": ["H"]},
    "BMET": {"N": ["H"]},
    "CMET": {"N": ["H"]},
    "TRP": {"NE1": ["HE1"], "N": ["H"]},
    "ATRP": {"NE1": ["HE1"], "N": ["H"]},
    "BTRP": {"NE1": ["HE1"], "N": ["H"]},
    "CTRP": {"NE1": ["HE1"], "N": ["H"]},
    "PHE": {"N": ["H"]},
    "APHE": {"N": ["H"]},
    "BPHE": {"N": ["H"]},
    "CPHE": {"N": ["H"]},
    "SER": {"OG": ["HG"], "N": ["H"]},
    "ASER": {"OG": ["HG"], "N": ["H"]},
    "BSER": {"OG": ["HG"], "N": ["H"]},
    "CSER": {"OG": ["HG"], "N": ["H"]},
    "THR": {"OG1": ["HG1"], "N": ["H"]},
    "ATHR": {"OG1": ["HG1"], "N": ["H"]},
    "BTHR": {"OG1": ["HG1"], "N": ["H"]},
    "CTHR": {"OG1": ["HG1"], "N": ["H"]},
    "TYR": {"OH": ["HH"], "N": ["H"]},
    "ATYR": {"OH": ["HH"], "N": ["H"]},
    "BTYR": {"OH": ["HH"], "N": ["H"]},
    "CTYR": {"OH": ["HH"], "N": ["H"]},
    "ASN": {"N": ["H"]},
    "AASN": {"N": ["H"]},
    "BASN": {"N": ["H"]},
    "CASN": {"N": ["H"]},
    "GLN": {"N": ["H"]},
    "AGLN": {"N": ["H"]},
    "BGLN": {"N": ["H"]},
    "CGLN": {"N": ["H"]},
    "LYS": {"N": ["H"]},
    "ALYS": {"N": ["H"]},
    "BLYS": {"N": ["H"]},
    "CLYS": {"N": ["H"]},
    "ARG": {"N": ["H"]},
    "AARG": {"N": ["H"]},
    "BARG": {"N": ["H"]},
    "CARG": {"N": ["H"]},
    "HIS": {"N": ["H"]},
    "AHIS": {"N": ["H"]},
    "BHIS": {"N": ["H"]},
    "CHIS": {"N": ["H"]},
    "ASP": {"N": ["H"]},
    "AASP": {"N": ["H"]},
    "BASP": {"N": ["H"]},
    "CASP": {"N": ["H"]},
    "GLU": {"N": ["H"]},
    "AGLU": {"N": ["H"]},
    "BGLU": {"N": ["H"]},
    "CGLU": {"N": ["H"]},
    "A": {"O2'": ["HO2'"]}, #"N6": ["H61", "H62"]
    "U": {"N3": ["H3"], "O2'": ["HO2'"]},
    "G": {"N1": ["H1"], "O2'": ["HO2'"]}, #"N2": ["H21", "H22"]
    "C": {"O2'": ["HO2'"]}, #"N4": ["H41", "H42"]
    # "DA": {"N6": ["H61", "H62"]},
    "DT": {"N3": ["H3"]},
    "DG": {"N1": ["H1"]}, #"N2": ["H21", "H22"]
    # "DC": {"N4": ["H41", "H42"]},
}

# apolar_vdw matlab ye sare atoms jo hai list me vo polar hai
HYDROPHOBIC_NEGLECTS = {
    "GLY": ["CA"],
    "AGLY": ["CA"],
    "BGLY": ["CA"],
    "CGLY": ["CA"],
    "ALA": ["CA"],
    "AALA": ["CA"],
    "BALA": ["CA"],
    "CALA": ["CA"],
    "VAL": ["CA"],
    "AVAL": ["CA"],
    "BVAL": ["CA"],
    "CVAL": ["CA"],
    "CYS": ["CA", "CB"],
    "ACYS": ["CA", "CB"],
    "BCYS": ["CA", "CB"],
    "CCYS": ["CA", "CB"],
    "PRO": ["CA"],
    "APRO": ["CA"],
    "BPRO": ["CA"],
    "CPRO": ["CA"],
    "LEU": ["CA"],
    "ALEU": ["CA"],
    "BLEU": ["CA"],
    "CLEU": ["CA"],
    "ILE": ["CA"],
    "AILE": ["CA"],
    "BILE": ["CA"],
    "CILE": ["CA"],
    "MET": ["CA", "CG", "CE"],
    "AMET": ["CA", "CG", "CE"],
    "BMET": ["CA", "CG", "CE"],
    "CMET": ["CA", "CG", "CE"],
    "TRP": ["CA"],
    "ATRP": ["CA"],
    "BTRP": ["CA"],
    "CTRP": ["CA"],
    "PHE": ["CA"],
    "APHE": ["CA"],
    "BPHE": ["CA"],
    "CPHE": ["CA"],
    "SER": ["CA", "CB"],
    "ASER": ["CA", "CB"],
    "BSER": ["CA", "CB"],
    "CSER": ["CA", "CB"],
    "THR": ["CA", "CB"],
    "ATHR": ["CA", "CB"],
    "BTHR": ["CA", "CB"],
    "CTHR": ["CA", "CB"],
    "TYR": ["CA"],
    "ATYR": ["CA"],
    "BTYR": ["CA"],
    "CTYR": ["CA"],
    "ASN": ["CA"],
    "AASN": ["CA"],
    "BASN": ["CA"],
    "CASN": ["CA"],
    "GLN": ["CA"],
    "AGLN": ["CA"],
    "BGLN": ["CA"],
    "CGLN": ["CA"],
    "LYS": ["CA", "CE"],
    "ALYS": ["CA", "CE"],
    "BLYS": ["CA", "CE"],
    "CLYS": ["CA", "CE"],
    "ARG": ["CA", "CD", "CZ"],
    "AARG": ["CA", "CD", "CZ"],
    "BARG": ["CA", "CD", "CZ"],
    "CARG": ["CA", "CD", "CZ"],
    "HIS": ["CA", "CB", "CE1", "CD2"],
    "AHIS": ["CA", "CB", "CE1", "CD2"],
    "BHIS": ["CA", "CB", "CE1", "CD2"],
    "CHIS": ["CA", "CB", "CE1", "CD2"],
    "ASP": ["CA"],
    "AASP": ["CA"],
    "BASP": ["CA"],
    "CASP": ["CA"],
    "GLU": ["CA"],
    "AGLU": ["CA"],
    "BGLU": ["CA"],
    "CGLU": ["CA"],
    "A": [
        "N1",
        "C2",
        "N3",
        "C4",
        "C5",
        "C6",
        "N6",
        "N7",
        "C8",
        "N9",
        "C1'",
        "C2'",
        "O2'",
        "C3'",
        "C4'",
        "O4'",
        "C5'",
        "O5'",
        "O3'",
    ],
    "G": [
        "N1",
        "C2",
        "N2",
        "N3",
        "C4",
        "C5",
        "C6",
        "N6",
        "O6",
        "N7",
        "C8",
        "N9",
        "C1'",
        "C2'",
        "O2'",
        "C3'",
        "C4'",
        "O4'",
        "C5'",
        "O5'",
        "O3'",
    ],
    "U": [
        "N1",
        "C2",
        "N3",
        "C4",
        "C6",
        "O2",
        "O4",
        "C1'",
        "C2'",
        "O2'",
        "C3'",
        "C4'",
        "O4'",
        "C5'",
        "O5'",
        "O3'",
    ],
    "C": [
        "N1",
        "C2",
        "N3",
        "C4",
        "C6",
        "O2",
        "N4",
        "C1'",
        "C2'",
        "O2'",
        "C3'",
        "C4'",
        "O4'",
        "C5'",
        "O5'",
        "O3'",
    ],
    "DA": [
        "N1",
        "C2",
        "N3",
        "C4",
        "C5",
        "C6",
        "N6",
        "N7",
        "C8",
        "N9",
        "C1'",
        "C2'",
        "O2'",
        "C3'",
        "C4'",
        "O4'",
        "C5'",
        "O5'",
        "O3'",
    ],
    "DG": [
        "N1",
        "C2",
        "N2",
        "N3",
        "C4",
        "C5",
        "C6",
        "N6",
        "O6",
        "N7",
        "C8",
        "N9",
        "C1'",
        "C2'",
        "O2'",
        "C3'",
        "C4'",
        "O4'",
        "C5'",
        "O5'",
        "O3'",
    ],
    "DT": [
        "N1",
        "C2",
        "N3",
        "C4",
        "C6",
        "O2",
        "O4",
        "C1'",
        "C2'",
        "O2'",
        "C3'",
        "C4'",
        "O4'",
        "C5'",
        "O5'",
        "O3'",
    ],
    "DC": [
        "N1",
        "C2",
        "N3",
        "C4",
        "C6",
        "O2",
        "N4",
        "C1'",
        "C2'",
        "O2'",
        "C3'",
        "C4'",
        "O4'",
        "C5'",
        "O5'",
        "O3'",
    ],
}

for key, value in HYDROPHOBIC_NEGLECTS.items():
    HYDROPHOBIC_NEGLECTS[key]: value.append("C")

S_BOND = {"CYS": "SG"}

# VDW_CHAIN1 = {
#     "GLY": ["CA"],
#     "AGLY": ["CA"],
#     "BGLY": ["CA"],
#     "CGLY": ["CA"],
#     "ALA": ["CA"],
#     "AALA": ["CA"],
#     "BALA": ["CA"],
#     "CALA": ["CA"],
#     "VAL": ["CA"],
#     "AVAL": ["CA"],
#     "BVAL": ["CA"],
#     "CVAL": ["CA"],
#     "CYS": ["CA", "CB"],
#     "ACYS": ["CA", "CB"],
#     "BCYS": ["CA", "CB"],
#     "CCYS": ["CA", "CB"],
#     "PRO": ["CA"],
#     "APRO": ["CA"],
#     "BPRO": ["CA"],
#     "CPRO": ["CA"],
#     "LEU": ["CA"],
#     "ALEU": ["CA"],
#     "BLEU": ["CA"],
#     "CLEU": ["CA"],
#     "ILE": ["CA"],
#     "AILE": ["CA"],
#     "BILE": ["CA"],
#     "CILE": ["CA"],
#     "MET": ["CA", "CG", "CE"],
#     "AMET": ["CA", "CG", "CE"],
#     "BMET": ["CA", "CG", "CE"],
#     "CMET": ["CA", "CG", "CE"],
#     "TRP": ["CA"],
#     "ATRP": ["CA"],
#     "BTRP": ["CA"],
#     "CTRP": ["CA"],
#     "PHE": ["CA"],
#     "APHE": ["CA"],
#     "BPHE": ["CA"],
#     "CPHE": ["CA"],
#     "SER": ["CA", "CB"],
#     "ASER": ["CA", "CB"],
#     "BSER": ["CA", "CB"],
#     "CSER": ["CA", "CB"],
#     "THR": ["CA", "CB"],
#     "ATHR": ["CA", "CB"],
#     "BTHR": ["CA", "CB"],
#     "CTHR": ["CA", "CB"],
#     "TYR": ["CA"],
#     "ATYR": ["CA"],
#     "BTYR": ["CA"],
#     "CTYR": ["CA"],
#     "ASN": ["CA"],
#     "AASN": ["CA"],
#     "BASN": ["CA"],
#     "CASN": ["CA"],
#     "GLN": ["CA"],
#     "AGLN": ["CA"],
#     "BGLN": ["CA"],
#     "CGLN": ["CA"],
#     "LYS": ["CA", "CE"],
#     "ALYS": ["CA", "CE"],
#     "BLYS": ["CA", "CE"],
#     "CLYS": ["CA", "CE"],
#     "ARG": ["CA", "CD"],
#     "AARG": ["CA", "CD"],
#     "BARG": ["CA", "CD"],
#     "CARG": ["CA", "CD"],
#     "HIS": ["CA", "CB", "CE1", "CD2"],
#     "AHIS": ["CA", "CB", "CE1", "CD2"],
#     "BHIS": ["CA", "CB", "CE1", "CD2"],
#     "CHIS": ["CA", "CB", "CE1", "CD2"],
#     "ASP": ["CA"],
#     "AASP": ["CA"],
#     "BASP": ["CA"],
#     "CASP": ["CA"],
#     "GLU": ["CA"],
#     "AGLU": ["CA"],
#     "BGLU": ["CA"],
#     "CGLU": ["CA"],
# }


# VDW_CHAIN2 = {
#     "GLY": ["CA"],
#     "AGLY": ["CA"],
#     "BGLY": ["CA"],
#     "CGLY": ["CA"],
#     "ALA": ["CA", "CB"],
#     "AALA": ["CA", "CB"],
#     "BALA": ["CA", "CB"],
#     "CALA": ["CA", "CB"],
#     "VAL": ["CG1", "CA", "CG2", "CB"],
#     "AVAL": ["CG1", "CA", "CG2", "CB"],
#     "BVAL": ["CG1", "CA", "CG2", "CB"],
#     "CVAL": ["CG1", "CA", "CG2", "CB"],
#     "CYS": ["SG", "CA", "CB"],
#     "ACYS": ["CA", "CB"],
#     "BCYS": ["CA", "CB"],
#     "CCYS": ["CA", "CB"],
#     "PRO": ["CD", "CG", "CA", "CB"],
#     "APRO": ["CD", "CG", "CA", "CB"],
#     "BPRO": ["CD", "CG", "CA", "CB"],
#     "CPRO": ["CD", "CG", "CA", "CB"],
#     "LEU": ["CD2", "CD1", "CB", "CG", "CA"],
#     "ALEU": ["CD2", "CD1", "CB", "CG", "CA"],
#     "BLEU": ["CD2", "CD1", "CB", "CG", "CA"],
#     "CLEU": ["CD2", "CD1", "CB", "CG", "CA"],
#     "ILE": ["CG1", "CD1", "CB", "CA", "CG2"],
#     "AILE": ["CG1", "CD1", "CB", "CA", "CG2"],
#     "BILE": ["CG1", "CD1", "CB", "CA", "CG2"],
#     "CILE": ["CG1", "CD1", "CB", "CA", "CG2"],
#     "MET": ["SD", "CB", "CE", "CG", "CA"],
#     "AMET": ["CE", "CG", "CA", "CB"],
#     "BMET": ["CE", "CG", "CA", "CB"],
#     "CMET": ["CE", "CG", "CA", "CB"],
#     "TRP": ["CZ3", "CE3", "CH2", "CD1", "CB", "CZ2", "CA"],
#     "ATRP": ["CZ3", "CE3", "CH2", "CD1", "CB", "CZ2", "CA"],
#     "BTRP": ["CZ3", "CE3", "CH2", "CD1", "CB", "CZ2", "CA"],
#     "CTRP": ["CZ3", "CE3", "CH2", "CD1", "CB", "CZ2", "CA"],
#     "PHE": ["CE2", "CD2", "CZ", "CD1", "CB", "CE1", "CA"],
#     "APHE": ["CE2", "CD2", "CZ", "CD1", "CB", "CE1", "CA"],
#     "BPHE": ["CE2", "CD2", "CZ", "CD1", "CB", "CE1", "CA"],
#     "CPHE": ["CE2", "CD2", "CZ", "CD1", "CB", "CE1", "CA"],
#     "SER": ["CA", "CB"],
#     "ASER": ["CA", "CB"],
#     "BSER": ["CA", "CB"],
#     "CSER": ["CA", "CB"],
#     "THR": ["CA", "CG2", "CB"],
#     "ATHR": ["CA", "CG2", "CB"],
#     "BTHR": ["CA", "CG2", "CB"],
#     "CTHR": ["CA", "CG2", "CB"],
#     "TYR": ["CE2", "CD2", "CZ", "CD1", "CB", "CE1", "CA"],
#     "ATYR": ["CE2", "CD2", "CZ", "CD1", "CB", "CE1", "CA"],
#     "BTYR": ["CE2", "CD2", "CZ", "CD1", "CB", "CE1", "CA"],
#     "CTYR": ["CE2", "CD2", "CZ", "CD1", "CB", "CE1", "CA"],
#     "ASN": ["CA", "CB"],
#     "AASN": ["CA", "CB"],
#     "BASN": ["CA", "CB"],
#     "CASN": ["CA", "CB"],
#     "GLN": ["CG", "CA", "CB"],
#     "AGLN": ["CG", "CA", "CB"],
#     "BGLN": ["CG", "CA", "CB"],
#     "CGLN": ["CG", "CA", "CB"],
#     "LYS": ["CD", "CB", "CE", "CG", "CA"],
#     "ALYS": ["CD", "CB", "CE", "CG", "CA"],
#     "BLYS": ["CD", "CB", "CE", "CG", "CA"],
#     "CLYS": ["CD", "CB", "CE", "CG", "CA"],
#     "ARG": ["CD", "CG", "CA", "CB"],
#     "AARG": ["CD", "CG", "CA", "CB"],
#     "BARG": ["CD", "CG", "CA", "CB"],
#     "CARG": ["CD", "CG", "CA", "CB"],
#     "HIS": ["CE1", "CA", "CD2", "CB"],
#     "AHIS": ["CE1", "CA", "CD2", "CB"],
#     "BHIS": ["CE1", "CA", "CD2", "CB"],
#     "CHIS": ["CE1", "CA", "CD2", "CB"],
#     "ASP": ["CA", "CB"],
#     "AASP": ["CA", "CB"],
#     "BASP": ["CA", "CB"],
#     "CASP": ["CA", "CB"],
#     "GLU": ["CG", "CA", "CB"],
#     "AGLU": ["CG", "CA", "CB"],
#     "BGLU": ["CG", "CA", "CB"],
#     "CGLU": ["CG", "CA", "CB"],
# }

CHPI_2_PIPI = ["HIS", "TRP", "TYR", "PHE"]

VDW_CHECK = {
    "CH_pi",
    "N_S_OH-pi",
    "pi-pi stacking",
    "cation_pi",
    "anion_pi",
    "polar-pi",
    "lone_pair_pi",
}
